### ISSUE TITLE
Wont work for Unity 5

### ISSUE THREAD

**Issue by GavinRooney** [nicloay/unity-spine-importer#20]
Im not sure if this is just happening to me but I have updated to unity 5 and have only recently found this plugin. Can anyone confirm that it works with Unity 5? I am getting a few errors

Assets/UnitySpineImporter/Scripts/Editor/Util/SpineUtil.cs(52,25): error CS0246: The type or namespace name `AvatarMask' could not be found. Are you missing a using directive or an assembly reference?

Assets/UnitySpineImporter/Scripts/Editor/Util/SpineUtil.cs(417,50): error CS0619: `UnityEditor.AnimationUtility.SetAnimationType(UnityEngine.AnimationClip, UnityEditor.ModelImporterAnimationType)' is obsolete: `SetAnimationType is no longer supported'

Assets/UnitySpineImporter/Scripts/Editor/Util/SpineUtil.cs(1068,25): error CS0619: `UnityEditorInternal.AnimatorController' is obsolete: `AnimatorController is obsolete. Use UnityEditor.Animations.AnimatorController instead (UnityUpgradable).'

Thanks

**Comment by garrot** [comment]
Yes, it's not work with Unity 5. I hope Nicloay or somebody fix that. It seems an editor problem.
Meanwhile i use Unity 4 for export Spine animations (in fact i only use for this) and open the project with Unity 5, its very bizarre because you do it every time you want to export animations, but it works.

**Comment by nicloay** [comment]
fixed in 0.5 version
